### ISSUE TITLE
Is the Ergodox-EZ opensource?

### ISSUE THREAD

**Issue by dmgm** [ErgoDox-EZ/docs#13]
I've looked at other open source keyboards, and found downloadable PCB designs. I don't see that here. Are those designs available?

**Comment by rzetterberg** [comment]
@dmgm you can find the PCB designs for the Ergodox here: https://github.com/Ergodox-io/ErgoDox/tree/master/ErgoDOX%20pcb

You can also find the CAD-files for the original Ergodox case in that GitHub-project: ![Image of original Ergodox case](https://www.ergodox.io/img/ErgoDox-original-min.png)

Quote from the original ergodox webpage (https://www.ergodox.io/):

> The entire project (including this website) is open source, allowing you the freedom to modify and tweak the project as you see fit.

However I'm not sure about the openness of the Ergodox EZ's designs with additional changes to the original case, the metal legs and the hand rests.

**Comment by dmgm** [comment]
If I'm wrong tell me, but the Ergodox EZ had toolless change switch sockets. I believe using the kailh sockets. Use of that socket requires a PCB update. I havent downloaded and opened the ergodox-io pcbs, but I dont think they have been modified to use this alternative mechanism.

Hense my question as to whether the PCBs used by Ergodox-ez where open source. I dont this they are, but I woun't be surprised if people think they are buying an open source hardware keyboard.

**Comment by rzetterberg** [comment]
@dmgm I did not know that :+1: I assumed the Ergodox EZ used the original PCB design. 

Looking at the Ergodox EZ website it only mentions that the open-source firmware QMK is used, but nothing about the hardware designs. 

I guess we can assume that none of the hardware designs are open-source, since the website doesn't claim that they are and there are no repositories containing hardware designs.

**Comment by dmgm** [comment]
I think you are correct. I had hoped that this git repository was controlled by someone from ergodox-ez and I would get a definitive answer.

**Comment by rzetterberg** [comment]
@dmgm well, the owner of Ergodox EZ is @ezuk. So, he would be the person to ask for a definitive answer :slightly_smiling_face:

**Comment by dmgm** [comment]
@ezuk could you please provide a definitive answer?

**Comment by ezuk** [comment]
@dmgm let's see if we can get current pcb designs, checking with my partners.

**Comment by ezuk** [comment]
Just uploaded the schematics for V5!
