### ISSUE TITLE
"Default ErgoDox EZ Configuration" link is bad

### ISSUE THREAD

**Issue by jefftrull** [ErgoDox-EZ/docs#4]
It no longer points to a .hex file.  I did find a different file in the repo that may be the right one... would be good to know, for those of us who want to start with the default instead of configuring our own from scratch.

https://raw.githubusercontent.com/ErgoDox-EZ/reactor/master/lib/firmware/keyboard/ergodox_ez/keymaps/keymap_default.hex

**Comment by ezuk** [comment]
When I search through readme.markdown for "default" I don't see it at all... Would you mind sharing where you found the link?

**Comment by jefftrull** [comment]
[here](https://github.com/ErgoDox-EZ/docs/wiki/Existing-configurations), second row, second column of the table

**Comment by sethherr** [comment]
I can move the wiki to the readme so that it isn't spread out.

**Comment by jefftrull** [comment]
The issue isn't the layout but the fact that the link is 404 :)

**Comment by ezuk** [comment]
@sethherr that'd be good. In general this repo isn't getting a ton of love, need to think what to do about it.

**Comment by sethherr** [comment]
I moved the wiki into the readme and fixed the link
