### ISSUE TITLE
ergodox ez not waking up after sleep

### ISSUE THREAD

**Issue by qubitstx** [ErgoDox-EZ/docs#9]
Been having an issue with the Ergodox (with QMK) not waking up after the computer goes to sleep.  Forced to unplug, wait ~10 seconds, re-plug keyboard to get a keyboard reboot (led sequence flash), after a few seconds, the keyboard responds.  Can't do a quick plug/re-plug, nor does it work immediately. Doesn't seem to be a hardware setting--that same port works fine with other keyboards.  Is this something intrinsic to the Teensy microcontroller?

**Comment by ezuk** [comment]
First time I hear of something like this... Wanna open an issue on the QMK project? I'd love to hear Jack's thoughts, he might have some good ideas.

**Comment by qubitstx** [comment]
Sure, will do.
